runfile('C:/Users/B180093/.spyder-py3/allteam_resource2.py', wdir='C:/Users/B180093/.spyder-py3')
runfile('C:/Users/B180093/.spyder-py3/allteam_resource_wikicreate2.py', wdir='C:/Users/B180093/.spyder-py3')
runfile('C:/Users/B180093/.spyder-py3/user_dataDB_create.py', wdir='C:/Users/B180093/.spyder-py3')
runfile('C:/Users/B180093/.spyder-py3/allteam_resource2.py', wdir='C:/Users/B180093/.spyder-py3')
runfile('C:/Users/B180093/.spyder-py3/allteam_resource_wikicreate2.py', wdir='C:/Users/B180093/.spyder-py3')
print(data_resource)
total_time = worklog[worklog['team'] == team_code[0][0]]['time_spent'].sum()
print(total_time)
total_time = worklog[worklog['team'] == team_code[22][0]]['time_spent'].sum()
print(total_time)
total_time = worklog[worklog['team'] == team_code[22][0]]['time_spent'].sum()
team_time = worklog[(worklog['team'] == team_code[22][0]) & (worklog['project_key'] == team_code[22][2])]['time_spent'].sum()
tims_time = worklog[(worklog['team'] == team_code[22][0]) & (worklog['project_key'] == 'TIMS')]['time_spent'].sum()
print(team_time)
runfile('C:/Users/B180093/.spyder-py3/user_dataDB_create.py', wdir='C:/Users/B180093/.spyder-py3')
runfile('C:/Users/B180093/.spyder-py3/allteam_resource_wikicreate2.py', wdir='C:/Users/B180093/.spyder-py3')
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(data[3]['id'])
print(data[3]['key'])
print(data[3]['field'])
print(data[3]['fields'])
print(data[3]['fields'][0])
print(data[3]['fields'][0]['field'])
print(data[3]['fields'][0]['field']['id'] = '-2')
if data[3]['fields'][0]['field']['id'] == '-2':
    print(data[3]['fields'][0]['field']['id'])
if data[3]['fields'][0]['field']['id'] == '-2':
    print(data[3]['fields'][0]['field']['name'])
print(data[3]['fields'][0]['field']['name'])
if data[3]['fields'][0]['field']['id'] == -2:
    print(data[3]['fields'][0]['field']['name'])
if data[3]['fields'][0]['field']['id'] != -2:
    print(data[3]['fields'][0]['field']['name'])
print(data[data[3]['fields'][0]['field']['id'] == -2]['name'])
print(data[data[3]['fields'][0]['field']['id'] == -2])
print(data[data[3]['fields'][0]['field']['id'] == -2]['name'])
print(data[data[3]['fields'][0]['field']['id'] == -2]['id'])
print(data[3]['fields'][0]['field']['id'] == -2)
a=[]

if data[3]['fields'][0]['field']['id'] == -2:
    a.append(data[3]['fields'][0]['field']['name'])
    a.append(data[3]['fields'][0]['value']['value'])


print(a)
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(a)
print(data[3]['fields'][0]['value']['value'])
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(data[3]['fields'][8]['value']['value'])
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(type(data[3]['fields'][8]['value']['value']))
print(type(data[3]['fields'][7]['value']['value']))
print(data[3]['fields'][7]['value']['value'])
print(data[3]['fields'][8]['value'])
print(type(data[3]['fields'][8]['value']))
print(type(str(data[3]['fields'][8]['value'])))
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')

## ---(Thu Apr 16 13:53:23 2020)---
runfile('C:/Users/B180093/.spyder-py3/unit_test_origindata2.py', wdir='C:/Users/B180093/.spyder-py3')
print(page_list)
print(test_result_list)
print(test_result)
module_result = test_result.drop_duplicates(['Module_Name'], keep='last')
print(module_result)
print(module_result.values.tolist())
runfile('C:/Users/B180093/.spyder-py3/test2.py', wdir='C:/Users/B180093/.spyder-py3')
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(data[3]['fields'][0]['value']['value'])
print(data[3]['fields'][8]['value']['value'])
print(data[3]['fields'][8]['value']['value'].get())
print(data[3]['fields'][7]['value']['value'])
print(data[3]['fields'][8]['value']['value'])
print(data[3]['fields'][8]['value']['value'].items())
print(data[3]['fields'][7]['value']['value'].items())
print(data[3]['fields'][7]['value']['value'].get())
print(type(data[3]['fields'][7]['value']['value']))
print(type(data[3]['fields'][7]['value']))
print(data[3]['fields'][7]['value'].items())
print(data[3]['fields'][8]['value'].items())
print(data[3]['fields'][8]['value'])
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
runfile('C:/Users/B180093/.spyder-py3/test2.py', wdir='C:/Users/B180093/.spyder-py3')
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(project_data)
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(wiki_data_top + wiki_data_middle + wiki_data_bottom)
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(project_data)
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
runfile('C:/Users/B180093/.spyder-py3/page_body_storage_info.py', wdir='C:/Users/B180093/.spyder-py3')
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(len(project_data[0]))
print(len(project_data))
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(project_data[94])
print(project_data[93])
runfile('C:/Users/B180093/.spyder-py3/page_body_storage_info.py', wdir='C:/Users/B180093/.spyder-py3')
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')

## ---(Fri Apr 17 11:10:48 2020)---
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(project_data)
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(project_data)
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(data[0]['versions'])
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(project)
print(project_key)
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(type(url))
print(type(url.text))
data.append(url.text)
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(data)
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(project_key[0])
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')
print(data)
runfile('C:/Users/B180093/.spyder-py3/test.py', wdir='C:/Users/B180093/.spyder-py3')