import requests
import json

id_pw = {'os_username': 'b180093', 'os_password': 'infra4938hC!'}


user_kiwi = ['a7228208','add319','admin','ahyoung','ann.jeong','b020069','b030014','b170111','b180093','b210060','bgkim','bh.kim','biglight','bkshin','bluextal','ch.lee','ch.yoon','chandana.tumati','charlie.sim','cheon29588','chyoo','cwshin','cy.ryu','daehee','dalas.yoo','deviance','dg.cho','dh.ahn','dhkim','dhlee','dhlee_gaon','dhryu','dhyook','dkay.jin','dsbaek','dwayne.park','dykim0310','ehdtjsskfk1','ella.kim','flora.kim','gaenggyu','gaonchips','gibeom','go23lee','gsy703','gwansug_jang','hannah.choo','hckim','headline22','hjjang','hjju','hjkim','hkson','hmkang','hmso','holy22','hs.jo','hsh0224','hskim','hss','hsseon','hwchoi','hyeon04','hyewon.baek','hyjun','hyorim','hyoyong.jung','hyunsik.park','iloveuojy','issong','jaemin','jagadeesh.jonna','james','jay.kim','jay.shim','jbpark','jds5822','jekim','jg.oh','jh.bae','jh.kwon','jhchoi','jhjeon26','jhkim','jhkim34','jhlee','jhsung','jigi.kim','jinotox','jinsup.sim','jjigday','jjomi','jjun2008','john.oh','jongsang.choi','jordan.lee','jp.park','julliard.ahn','jungmo','justin.kim','jw.lee','jw.park','jwhong','jwseo','jyseo','kamillen','kamo','kdh3190','kenn','khlee1','khmoon','kimms','kimys','kingstreet','kj.joo','kjs3535','km.hong','kmg114','ksjkay','kspark','ksy10241','kw.kang','kyuheuk','leeboh','leedh','leesw','lemon1649','leo.lee','ljh5569','louis.go','lsbcoolman','lyma','mason.kim','mhshin','mongma','mooncheol.kee','mskong','mssong','muhammedafeef.khawas','murmuring','nhr','orionpark','ozoo317','pc1197','peace2joy','peter','peter.choi','ph614','pjh0314','pyb','qntek100','qrtkdgns','river.yeon','rndadmin','rscho','sblee','sckwon','scwoo','sdindra','sean.kim','seungpil.shim','sh.lee','shai.oh','shenjus','shlee77','shooo34','shum','sj.kim','sjjeong','sjlee','sjpark','sjw','skawls223','sklee','smwang','ssg','sujin7161','sunghu4865','sungminhan','supergate','swcho','swkim','ted.jeong','ted.kim','tejali.sonawane','tele_safety','telechips','thangle','tkkim','todd.park','tom.kim','tripti.a.jain','tuntable','tuynguyen','tyhuh','wang','wjko','wnguq1227','wolfks','wrkim','ws.choi','wypark','xodud952','yhchoi','yhkim602','yhlim','yjsong','ymk7288','yongtae','ysh1219','ysoh4011','ywk']
user_lemon = ['a7228208','add319','admin','ahyoung','ann.jeong','b020069','b030014','b180093','b210060','bgkim','bh.kim','biglight','bkshin','bluextal','ch.lee','ch.yoon','chandana.tumati','charlie.sim','cheon29588','chyoo','cwshin','cy.ryu','daehee','dalas.yoo','deviance','dg.cho','dh.ahn','dhkim','dhlee','dhlee_gaon','dhryu','dhyook','dkay.jin','dsbaek','dwayne.park','dykim0310','ehdtjsskfk1','ella.kim','flora.kim','gaenggyu','gaonchips','gibeom','go23lee','gsy703','gwansug_jang','hannah.choo','hckim','headline22','hjjang','hjju','hjkim','hkson','hmkang','hmso','holy22','hs.jo','hsh0224','hskim','hss','hsseon','hwchoi','hyeon04','hyewon.baek','hyjun','hyorim','hyoyong.jung','hyunsik.park','iloveuojy','issong','jaemin','jagadeesh.jonna','james','jay.kim','jay.shim','jbpark','jds5822','jekim','jg.oh','jh.bae','jh.kwon','jhchoi','jhjeon26','jhkim','jhkim34','jhlee','jhsung','jigi.kim','jinotox','jinsup.sim','jjigday','jjomi','jjun2008','john.oh','jongsang.choi','jordan.lee','jp.park','julliard.ahn','jungmo','justin.kim','jw.lee','jw.park','jwhong','jwseo','jyseo','kamillen','kamo','kdh3190','kenn','khlee1','khmoon','kimms','kimys','kingstreet','kj.joo','kjs3535','km.hong','kmg114','ksjkay','kspark','ksy10241','kw.kang','kyuheuk','leeboh','leedh','leesw','lemon1649','leo.lee','ljh5569','louis.go','lsbcoolman','lyma','mason.kim','mhshin','mongma','mooncheol.kee','mskong','mssong','muhammedafeef.khawas','murmuring','nhr','orionpark','ozoo317','pc1197','peace2joy','peter','peter.choi','ph614','pjh0314','pyb','qntek100','qrtkdgns','river.yeon','rndadmin','rscho','sblee','sckwon','scwoo','sdindra','sean.kim','seungpil.shim','sh.lee','shai.oh','shenjus','shlee77','shooo34','shum','sj.kim','sjjeong','sjlee','sjpark','sjw','skawls223','sklee','smwang','ssg','sujin7161','sunghu4865','sungminhan','supergate','swcho','swkim','ted.jeong','ted.kim','tejali.sonawane','tele_safety','telechips','thangle','tkkim','todd.park','tom.kim','tripti.a.jain','tuntable','tuynguyen','tyhuh','wang','wjko','wnguq1227','wolfks','wrkim','ws.choi','wypark','xodud952','yhchoi','yhkim602','yhlim','yjsong','ymk7288','yongtae','ysh1219','ysoh4011','ywk']


'''
for i in range(0, len(user_list)):
    url = 'https://lemon.telechips.com:8443/rest/api/2/user?username=' + user_list[i]
    r = requests.get(url, id_pw)
    data = json.loads(r.text)
    print(data['displayName'] + ',' + data['name'] + ',' + data['emailAddress'])
'''

url = 'https://lemon.telechips.com:8443/rest/api/2/user?username=b180093'
r = requests.get(url, id_pw)
data = json.loads(r.text)
print(data)